# Generated by Django 4.0.2 on 2022-02-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(related_name='publicaciones_vinculadas', to='blog.Category', verbose_name='Categorias'),
        ),
    ]
