# Generated by Django 4.0.2 on 2022-03-08 02:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_alter_webpage_options_webpage_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido'),
        ),
    ]
